package(default_visibility = ["//visibility:public"])

cc_library(
    name = "zlib",

    srcs = [
      'adler32.c',
      'deflate.c',
      'gzlib.c',
      'gzread.c',
      'gzwrite.c',
      'trees.c',
      'zutil.c',
      'inffast.c',
      'inflate.c',
      'inftrees.c',
      'infback.c',
      'gzclose.c',
      'uncompr.c',
      'compress.c',
      'crc32.c',
    ],
    hdrs = [
      'deflate.h',
      'gzguts.h',
      'trees.h',
      'zlib.h',
      'zutil.h',
      'inffast.h',
      'inffixed.h',
      'inflate.h',
      'inftrees.h',
      'zconf.h',
      'crc32.h',
    ],
    includes = [ 
      '.' 
    ],
)
